# Generated by Django 5.0.3 on 2024-03-04 17:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=2005, message='Year should be from 2005 onwards.'), django.core.validators.MaxValueValidator(limit_value=2023, message='Year should not exceed 2023.')])),
                ('horsepower', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=100, message="We can't rent car with less than 100 horsepowers."), django.core.validators.MaxValueValidator(limit_value=800, message="We can't rent car with more than 800 horsepowers.")])),
                ('fuel_consumption', models.DecimalField(decimal_places=1, max_digits=2)),
                ('daily_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=100, message="We can't rent car with daily price less than 100$."), django.core.validators.MaxValueValidator(limit_value=2000, message="We can't rent car with daily price more than 2000$.")])),
                ('available_to_rent', models.BooleanField(default=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.insurance')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.car')),
            ],
        ),
    ]
