# Generated by Django 5.0.3 on 2024-03-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_consumption',
            field=models.IntegerField(),
        ),
    ]
