# Generated by Django 5.0.3 on 2024-03-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_renter_max_daily_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renter',
            name='max_daily_budget',
        ),
    ]
